[package]
name = "gablet_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gablet_api = { path = "../gablet_api" }
rand = { version = "0.8.5", features = ["min_const_gen"] }
tokio = "1.28.2"
