-- Your SQL goes here
ALTER TABLE users
ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_login TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;